[package]
name = "miros"
version = "0.1.0"
edition = "2021"
description = "A modern ELF interpreter (dynamic linker/loader) written in Rust"

[build]
rustc = "rustc_wrapper_script.sh"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
